### ISSUE TITLE
CJKunderlinecolor undefined

### ISSUE THREAD

**Issue by zdxxwqx** [marscfeng/cugThesis#1]
when running the latex code, there is an ERROR in the cugthesis.cls:  \CJKunderlinecolor undefined.
so, how to solve it?

**Comment by marscfeng** [comment]
If you'r using MAC, I would suggest you to update your texlive before running the shell script. Are you using CTEX? I did not try to compile this template on Windows, i mean there could be some tiny issues if you apply this on Windows. But one of my friend did this without  too much effects on modification the codes.

**Comment by zdxxwqx** [comment]
yes, i'm using CTEX and do you know any possible solutions? or if I want to solve this problem, where can I find some useful message?

**Comment by marscfeng** [comment]
You may want to try texlive rather than CTEX. check this issue [CJK error](https://github.com/mohuangrui/ucasthesis/issues/110)
